mongo:
  image: mongo

site:
  build: .
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app
    - /home/app/node_modules
  links:
    - mongo
  environment:
   - MONGO_URI=mongodb://mongo:27017/site
   - NODE_ENV=development
