version: '2.1'

services:

  # This file is for the continunous integration testing process.
  # It is meant to start with a freshly cloned repository.
  # It will start with a minimum linux image running node,
  # install package apis, and dependencies, run tests, and in
  # the end, leave us with a minimal production ready docker container
  # that can be run in our cluster.

  # I left the env variables as examples of things
  # you may want to pass in from the CI server
  base:
    image: node:10
    volumes:
      - .:/home/app
    working_dir: /home/app

  # output: node_modules/ with all dependencies
  install:
    extends:
      service: base
    command: npm i
